### ISSUE TITLE
⭐ titles

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#10]
### Задание
- Написать стили для нескольких Title, брать из figma, из UI-KIT, типография
- Сделать адаптив (только для h1)

### Исполнитель: *[Иван](https://github.com/isvakulenko) @isvakulenko *
Как возьмешь задачу, впиши себя сюда по образцу 

### К работе приступил: *21:30 *

___
### Примечание
- Стили можно занести в переменные в файле index.css #root
- Это в целом легкая работа, так что можно сразу без моей проверки добавлять их в папку styles и пушить в нашу ветку

**Comment by isvakulenko** [comment]
взял

**Comment by chyVacheck** [comment]
На тебе было задание сделать переменны для стилей по заглавиям, я увидел, что ты создал универсальный блок, но нужно было сделать еще кое-что, а именно сделать 5 стиля, полностью готовых, под h1-h4 и текст, что бы другие могли не смотреть в брифе размеры, а брать и использовать уже готовые, понимаешь ?

Я попрошу тебя доделать это задание до конца, как сделаешь кинь pull request на мерж с веткой фронт
