### ISSUE TITLE
⭐  Component visitka

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#11]
### Задание
- Сверстать компонент Visitka (в том стиле, который мы решили на созвоне)
- Сделать к нему полный адаптив
- Сделать функционал под комментарии
  - Для начала проверьте что задача по созданию "Обратной связи" уже готова
  - Добавь функцию по открытию Обратной связи в данной визитке

### К работе приступил: *02/04/2023 22:30*
Ренат приступил 06/04/2023 18:00

___
### Примечание
- После выполнения работы написать мне, я проверю
- Данные для визитки брать из пропсов
- Пока что api не используем
- Если я забыл затронуть тему "стиля", для компонентов пишите в пачке @chyVacheck

**Comment by SmthOfValue** [comment]
https://github.com/FenixDeveloper/ya-visitka_c7/pull/98

Пока стоит заглушка вместо Feedback. Нужно выяснить, какие стили у фидбэка для более маленьких экранов
