### ISSUE TITLE
📲 Исправить замечания в Comments Controller

### ISSUE THREAD

**Issue by SergeyKazarinov** [FenixDeveloper/ya-visitka_c7#150]
### Задание
- [ ] Обработать ситуацию, когда возникает ошибка валидации на стороне БД (если такие имеются).
- [ ] Обработать ситуацию, когда передан невалидный ID
- [ ] Добавить значения по умолчанию, если они где-то отсутствуют. И убрать дефолтные значения из celebrate валидации

![Image](https://user-images.githubusercontent.com/99301610/232027735-bfc6dc10-4e4d-4c32-b2dd-83e28df15244.png)

### К работе приступила: *

___

**Comment by GeniaV** [comment]
При создании комментария, если в базе не указан например, профайл, возникает ошибка. Проверьте также на работу при отсутствии других полей. 
**Это относится к задаче Андрея по добавлению комментриев.**
