### ISSUE TITLE
📲  Создать модель пользователя

### ISSUE THREAD

**Issue by SergeyKazarinov** [FenixDeveloper/ya-visitka_c7#18]
### Задание
- Изучить документацию [дискриминатора](https://mongoosejs.com/docs/discriminators.html) и [применение дискриминатора к вложенным коллекциям](http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators.html).
- Разделить модель пользователя на [отдельные схемы](https://mongoosejs.com/docs/subdocs.html).
- Реализовать статический метод получения пользователя по email
- Изучить методы агрегации для сортировки данных. Используются  методы unwind и sort. [Aggregation Operations](https://www.mongodb.com/docs/manual/aggregation/)

### К работе после первого ревью: *13:00 02.04.23*
___
### Примечание
- Не забудьте правильно настроить индексы по документу.
- учитывать валидацию отдельных полей. Информация в брифе

**Comment by SergeyKazarinov** [comment]
Сделаны заготовки с кодом:
1. Модель пользователя разделена на отдельные схемы 
2. Реализован статический метод получения пользователя по email.
3. Для базовой схемы реакций используется discriminatorKey
4. Сделана валидация отдельных полей
 

ЧТО ПЛАНИРУЕТСЯ
Реализовать метод агрегации для сортировки данных.
Создать ветку, добавить код и проверить его работоспособность.
Не уверена в некоторых вещах, поэтому надо тестировать.

**Comment by GeniaV** [comment]
Внесены правки после первого ревью.
