### ISSUE TITLE
📲 Создать comments controller

### ISSUE THREAD

**Issue by SergeyKazarinov** [FenixDeveloper/ya-visitka_c7#21]
### Задание
- Добавить роуты для /comments. Методы GET, DELETE (для конкретного пользователя)
- Реализовать соответствюущие контроллеры для роутов соглассно [документации](https://editor.swagger.io/)

### К работе приступила: *21:10 03.04.2023*

___
### Примечание
Подробное [OpenApi](https://editor.swagger.io/)

**Comment by GeniaV** [comment]
.
