### ISSUE TITLE
⭐ Page Login

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#32]
### Задание
- Сверстать компонент Login (в том стиле, который мы решили на созвоне)
- Сделать к нему полный адаптив
- Сделать функционал перехода на страницу яндекса

### Исполнитель: *[Дима](https://github.com/chyVacheck) @chyVacheck (пример)*
[Артём](https://github.com/Artrudjob) @Artrudjob 

### К работе приступил: *19:10 (пример)*
Как возьмешь задание напиши время по мск, когда взял задачу

___
### Примечание
- После выполнения работы проверить внимательно на адаптив, и если все ок запушить в нашу ветку
- Если я забыл затронуть тему "стиля", для компонентов пишите в пачке @chyVacheck

**Comment by Artrudjob** [comment]
Беру, сделаю в пятницу-субботу
