### ISSUE TITLE
⭐  Component inputs

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#36]
### Задание
- Сверстать компонент Inputs
- Сделать его полные стили (см. макет)
- Сделать несколько все типы (см. макет)
- Компонент должен быть универсальным (по большей части это относиться к стилям и пропсам)
- Сделать логику изменения значения инпута, можно сделать кастомный хук, можно прописать внутри компонента

### Исполнитель: *[Настя](https://github.com/Akvela) @Akvela*
Как возьмешь задачу, впиши себя сюда по образцу 

### К работе приступил: *22:00/30.03.23*
Как возьмешь задание напиши время и дату по мск, когда взял/а задачу
___
### Примечание
- Работать в отдельной ветке
- Информацию передавать через пропсы
- Если еще, что-то нужно, то все брать из constants, никакого хардкора в коде
- После выполнения работы сделать запрос на слияние веток, если беда зовем меня

**Comment by Akvela** [comment]
[Пулл реквест](https://github.com/FenixDeveloper/ya-visitka_c7/pull/57)
