### ISSUE TITLE
⭐ add some stuff

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#4]
### Задание
 - Скачать все иконки из блока "UI-KIT" и добавить в папку icons в папке assets 
   - Если папок еще нет, то создать
 - В главном index.css файле в блок root добавить переменные цветов из макета, они находятся в блоке "Палитра"

### Исполнитель: [Настя](https://github.com/Akvela) @Akvela
Как возьмешь задачу, впиши себя сюда по образцу 

### К работе приступил: 12:30
Как возьмешь задание напиши время по мск, когда взял задачу

### Фактическое время выполнения работы: сложно сказать из-за возникших накладок
- [x] Студент уложился во время 
___
### Примечание
- Это в целом легкая работа, так что можно сразу без моей проверки пушить в нашу ветку

**Comment by Akvela** [comment]
взяла на завтра

**Comment by Akvela** [comment]
[Ссылка на пул реквест](https://github.com/FenixDeveloper/ya-visitka_c7/pull/35)
