### ISSUE TITLE
⭐ init project

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#5]
### Задание
- Создать приложение на реакт (в папке frontend)
- Убрать все лишние файлы и комментарии 
- Создать файловую структуру (ту что обсуждали на созвоне)
- Настроить роутеры (добавить к каждой странице свой роутер, пока что простой, не нужно защищенный)
- Добавить какой никакой Readme.md указать команду (в файле frontend)

### К работе приступил: 29.03.2023 20:30 
Как возьмешь задание напиши время по мск, когда взял задачу

### Фактическое время выполнения работы: примерно один час
- [x] Студент уложился во время 

___
### Примечание
- Это в целом легкая работа, так что можно сразу без моей проверки пушить в нашу ветку
- Если я забыл затронуть тему "файловую  структуру ", для проекта пишите в пачке @chyVacheck

**Comment by SmthOfValue** [comment]
Запушил проект в ветку frontend.
Роуты добавлены.
Файловая структура заведена.
Readme фронтенда заполнен.
Лишние файлы и комменты удалил.
