### ISSUE TITLE
⭐  Component header

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#7]
### Задание
- Сверстать компонент header
- Сделать к нему полный адаптив

### Исполнитель: *[Антон](https://github.com/AntonAduisky) @AntonAduisky*
Как возьмешь задачу, впиши себя сюда по образцу 

### К работе приступил: *18:30*
___
### Примечание
- Информацию о пользователе брать только из пропсов
- Проверить есть ли компонент Login (без него нельзя делать задачу)
- Пока нет api информацию о пользователе можно прописать в пропсах по типу 
```js
function Header(
  user = {
    name: "Константин Константинович",
    avatar: avatar // временно взять из constant
  }) {
// код компонента
}
```
- Если еще, что-то нужно, то все брать из constants, никакого хардкора в коде
- Если я забыл затронуть тему "стиля", для компонентов пишите в пачке @chyVacheck

**Comment by AntonAduisky** [comment]
Взял

**Comment by AntonAduisky** [comment]
Взял
