### ISSUE TITLE
⭐ Protected router

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#86]
### Задание
Компонент должен работать по следующему принципу
- Если все ок то показывает детей, ту страницу, что он защищает
- Если настройки не удовлетворены, идет переброс на ту страницу, что была указана в настройках

### Структура
- Принимает следующие значения:
  + Статус который должен иметь пользователь что бы зайти на эту страницу
  + Статут текущего пользователя (брать из контекста)
  + Страницу на которую отправлять пользователя если он не перешел

### Обрати внимание
- У нас всегда есть почта у пользователя (не писать в константах пустое значение) в макете косяк
- Делаем коммиты по смыслу, не нужно пихать много чего в 1 коммит

### К работе приступил: *07.04.23*
Как я приму таск "компонет визитка" напиши дату по мск, когда сел за задачу

___
### Примечание
- Работать в отдельной ветке
- После выполнения работы сделать запрос на слияние веток, если беда зовем меня

**Comment by SmthOfValue** [comment]
https://github.com/FenixDeveloper/ya-visitka_c7/pull/105

добавлен userStatus для пользователя, защищенный рут проводит проверку по этому полю. Добавлены защищенные руты на все пути кроме логина
