### ISSUE TITLE
⭐  Component buttons

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#9]
### Задание
- Сверстать компонент Button
- Сделать его полные стили (см. макет)

### Исполнитель:  [Ренат](https://github.com/smthofvalue) @smthofvalue
Как возьмешь задачу, впиши себя сюда по образцу 

### К работе приступил: 31.03.2023 15:40
Как возьмешь задание напиши время по мск, когда взял задачу
___
### Примечание
- Информацию о кнопке брать только из пропсов, тип, текст и все такое
- Пока нет api информации о пользователе можно прописать в пропсах по типу 
```js
function Button(
  onClick = () => {
    console.log('the button was pressed')
  })
// код компонента
}
```
- Если еще, что-то нужно, то все брать из constants, никакого хардкора в коде
- После выполнения работы проверить через создание тестовых кнопок (в коммит их не нужно пушить) если все ок то убираем тесты и пушим, если беда зовем меня

**Comment by SmthOfValue** [comment]
Добавил компонент Button. 
протестировать можно, добавив компонент <Button onClick={() => console.log('нажалась кнопка')}>Text</Button> с разными пропсами
Принимает пропсы размера (small, medium, large), onClick, htmlType (button, submit, reset), children. Стили зависят от размера.

Пулл реквест: https://github.com/FenixDeveloper/ya-visitka_c7/pull/48
