### ISSUE TITLE
⭐ Page profile settings

### ISSUE THREAD

**Issue by chyVacheck** [FenixDeveloper/ya-visitka_c7#97]
### Задание
- Полная верстка страницы
- Адаптивная верстка (и резиновая)
- С использованием валидации

### Обрати внимание
- Пока что submit функции нет
- Делаем коммиты по смыслу, не нужно пихать много чего в 1 коммит

### К работе приступил: *07.04.23*
Напиши дату по мск, когда сел за задачу

___
### Примечание
- Работать в отдельной ветке
- После выполнения работы сделать запрос на слияние веток, если беда зовем меня

**Comment by Akvela** [comment]
[Пулл реквест](https://github.com/FenixDeveloper/ya-visitka_c7/pull/119)
